config/routes.rb
C2do::Application.routes.draw do
  
  resources :sharings

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users

  resources :lists, only: [:index]
  
 	namespace :my, path: "my" do
 		resources :lists, shallow: true do
 			collection do
        post :sort
      end
      resources :todos, shallow: true do
        member do
          put :update_state
        end
  			resources :tasks, shallow: true
  		end
  	end
  end

end

app/models/sharing.rb
class Sharing < ActiveRecord::Base
end

app/controllers/sharings_controller.rb
class SharingsController < ApplicationController
  before_action :set_sharing, only: [:show, :edit, :update, :destroy]

  # GET /sharings
  # GET /sharings.json
  def index
    @sharings = Sharing.all
  end

  # GET /sharings/1
  # GET /sharings/1.json
  def show
  end

  # GET /sharings/new
  def new
    @sharing = Sharing.new
  end

  # GET /sharings/1/edit
  def edit
  end

  # POST /sharings
  # POST /sharings.json
  def create
    @sharing = Sharing.new(sharing_params)

    respond_to do |format|
      if @sharing.save
        format.html { redirect_to @sharing, notice: 'Sharing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sharing }
      else
        format.html { render action: 'new' }
        format.json { render json: @sharing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharings/1
  # PATCH/PUT /sharings/1.json
  def update
    respond_to do |format|
      if @sharing.update(sharing_params)
        format.html { redirect_to @sharing, notice: 'Sharing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sharing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharings/1
  # DELETE /sharings/1.json
  def destroy
    @sharing.destroy
    respond_to do |format|
      format.html { redirect_to sharings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sharing
      @sharing = Sharing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sharing_params
      params.require(:sharing).permit(:user_id, :recipient_id, :description, :shareable_id)
    end
end

app/helpers/sharings_helper.rb
module SharingsHelper
end

app/views/sharings/_form.html.haml
= simple_form_for(@sharing) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :recipient_id
    = f.input :description
    = f.input :shareable_id

  .form-actions
    = f.button :submit

app/views/sharings/edit.html.haml
%h1 Editing sharing

= render 'form'

= link_to 'Show', @sharing
\|
= link_to 'Back', sharings_path

app/views/sharings/index.html.haml
%h1 Listing sharings

%table
  %tr
    %th User
    %th Recipient
    %th Description
    %th Shareable
    %th
    %th
    %th

  - @sharings.each do |sharing|
    %tr
      %td= sharing.user_id
      %td= sharing.recipient_id
      %td= sharing.description
      %td= sharing.shareable_id
      %td= link_to 'Show', sharing
      %td= link_to 'Edit', edit_sharing_path(sharing)
      %td= link_to 'Destroy', sharing, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sharing', new_sharing_path

app/views/sharings/new.html.haml
%h1 New sharing

= render 'form'

= link_to 'Back', sharings_path

app/views/sharings/show.html.haml
%p#notice= notice

%p
  %b User:
  = @sharing.user_id
%p
  %b Recipient:
  = @sharing.recipient_id
%p
  %b Description:
  = @sharing.description
%p
  %b Shareable:
  = @sharing.shareable_id

= link_to 'Edit', edit_sharing_path(@sharing)
\|
= link_to 'Back', sharings_path