config/routes.rb
C2do::Application.routes.draw do
  
  resources :sharings

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users

  resources :lists, only: [:index]
  
 	namespace :my, path: "my" do
 		resources :lists, shallow: true do
 			collection do
        post :sort
      end
      resources :todos, shallow: true do
        member do
          put :update_state
        end
  			resources :tasks, shallow: true
  		end
  	end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :todo
	belongs_to :creator_user, class_name: "User", foreign_key: "creator_user_id"
	belongs_to :assigned_user, class_name: "User", foreign_key: "assigned_user_id"
	
	delegate :list, to: :todo, allow_nil: true

	validates_presence_of :name, :creator_user_id
	validates :position, numericality: { greater_than_or_equal_to: 0 }

  include RankedModel
  ranks :position
end

app/controllers/my/lists_controller.rb
class My::ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists.rank(:position)
    @assigned_todos = current_user.assigned_todos.count
    @created_todos  = current_user.created_todos.count
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @todos = @list.todos.includes(:tasks)
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
      
    respond_to do |format|
      if @list.save
        @subscription = @list.list_subscriptions.create(user_id: current_user.id)
        format.html { redirect_to [:my, @list], notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to [:my, @list], notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST lists([:ids])
  def sort
    params[:list].each_with_index do |id, index|
      List.where(id: id).update_all({position: index+1})
    end
    render nothing: true
  end


  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to my_lists_url() }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @user = current_user
      @list = @user.lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :position)
    end
end

app/controllers/my/tasks_controller.rb
class My::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_todo, only: [:index, :create, :new]
  # before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @todo.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @todo = @task.todo
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to [:my, @task], notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to [:my, @task], notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to my_todo_tasks_url(@todo) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.includes(:todo).find(params[:id])
      @todo = @task.todo
      @list = @todo.list
    end

    def set_todo
      @todo = Todo.includes(:list).find(params[:todo_id])
      @list = @todo.list
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params[:task][:todo_id] = params[:todo_id].present? ? params[:todo_id] : @todo.id.to_s
      params[:task][:creator_user_id] = current_user.id if current_user.present? && request.method.to_s == "POST"
      params.require(:task).permit(:name, :position, :due_at, :shared_state, :progress_state, :shared_state, :predue_at, :overdue_at, :todo_id, :creator_user_id)
    end
end

app/controllers/my/todos_controller.rb
class My::TodosController < ApplicationController
 
  include Concerns::State

  before_action :set_resource, only: [:update_state]
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_list, only: [:index, :new, :create]
  before_action :authenticate_user!

  # GET /todos
  # GET /todos.json
  def index
    @todos = @list.todos.includes(:tasks).load
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to [:my, @todo], notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to [:my, @todo], notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @list = @todo.list
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to my_list_todos_url(@list) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.includes(:list).find(params[:id])
      @list = @todo.list
    end

    # Use callbacks to set parent for not shallowed routes.
    def set_list
      @list = List.find(params[:list_id])
    end

    # to have access to the @resource instance variable in concerns
    def set_resource
      Logger.new(STDOUT).info(">>>>>>>>>>>>> request.parameters:: #{request.parameters}")
      @resource = Todo.includes(:list).find(params[:id])
      Logger.new(STDOUT).info(">>>>>>>>>>>>> request.parameters:: #{request.parameters}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      if request.method.to_s == "POST"
        params[:todo][:list_id] = params[:list_id].present? ? params[:list_id] : @list.try(:id).to_s
        params[:todo][:creator_user_id] = current_user.id if current_user.present? 
        params[:todo][:position] = @list.todos.maximum(:position)+1 unless params[:todo][:position]
      end
      params.require(:todo).permit(:name, :position, :list_id, :creator_user_id, :assigned_user_id, :due_at, :predue_at, :overdue_at, :shared_state, :progress_state)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/my/tasks/_form.html.haml
- if @task.new_record?
  = simple_form_for([:my, @todo, @task]) do |f|
    = f.error_notification
  
    .form-inputs
      = f.input :name
      = f.input :position
      = f.input :due_at, as: :string, input_html: {data: {"date-startdate" => 3.days.ago }}
      = f.input :shared_state
      = f.input :progress_state
      = f.input :shared_state
      = f.input :predue_at, as: :string, input_html: {data: {"date-startdate" => 3.days.ago }}
      = f.input :overdue_at, as: :string, input_html: {data: {"date-startdate"=> 3.days.ago}}
  
    .form-actions
      = f.button :submit

- else
  = simple_form_for([:my, @task]) do |f|
    = f.error_notification
  
    .form-inputs
      = f.input :name
      = f.input :position
      = f.input :due_at, as: :string, input_html: {data: {"date-startdate" => 3.days.ago}}
      = f.input :shared_state
      = f.input :progress_state
      = f.input :shared_state
      = f.input :predue_at, as: :string, input_html: {data: {"date-startdate" => 3.days.ago }}
      = f.input :overdue_at, as: :string, input_html: {data: {"date-startdate" => 3.days.ago }}
  
    .form-actions
      = f.button :submit

app/views/my/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Back', my_todo_tasks_path(@todo)

app/views/my/tasks/index.html.haml
%h1= "#{link_to @list.name, my_list_path(@list)} >> #{@todo.name}"

%table
  %tr
    %th Name
    %th Position
    %th Due at
    %th Shared state
    %th Progress state
    %th Predue at
    %th Overdue at
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.name
      %td= task.position
      %td= task.due_at
      %td= task.shared_state
      %td= task.progress_state
      %td= task.predue_at
      %td= task.overdue_at
      %td= link_to 'Show', [:my, task]
      %td= link_to 'Edit', edit_my_task_path(task)
      %td= link_to 'Destroy', [:my, task], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_my_todo_task_path(@todo)

app/views/my/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', my_todo_tasks_path(@todo)

app/views/my/tasks/show.html.haml
= @list.name

%p
  %b Name:
  = @task.name
%p
  %b Position:
  = @task.position
%p
  %b Due at:
  = @task.due_at
%p
  %b Shared state:
  = @task.shared_state
%p
  %b Progress state:
  = @task.progress_state
%p
  %b Predue at:
  = @task.predue_at
%p
  %b Overdue at:
  = @task.overdue_at

= link_to 'Edit', edit_my_task_path(@task)
\|
= link_to 'Back', my_todo_path(@todo)